### ISSUE TITLE
fix Tangram-ES load & draw issues

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#83] opened 2016-09-01 16:24 UTC
Tron is failing to load in tangram-ES

```
.706767 - WARNING sceneLoader.cpp:888: Duplicate DataSource: normals-elevation
0.721644 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.722112 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.722299 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.722852 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.726436 - WARNING sceneLoader.cpp:755: Invalid blend mode 'opaque'
0.726580 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.726731 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.726808 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.731538 - WARNING styleParam.cpp:144: Unknown StyleParam text:buffer:5px
0.731553 - WARNING styleParam.cpp:144: Unknown StyleParam text:move_into_tile:false
0.731575 - WARNING styleParam.cpp:144: Unknown StyleParam move_into_tile:false
0.732674 - WARNING sceneLoader.cpp:1306: Invalid  'filter':
'{min: 17, area: true}'
Assertion failed: (false), function filterCost, file /Users/patricio/Desktop/paparazzi/tangram-es/core/src/scene/filters.cpp, line 125.
```

`'{min: 17, area: true}'` probably caused by [this line on pois.yaml](https://github.com/tangrams/tron/blob/b7d8bae2e271eb22eca5545062d6f60cb3221479/layers/pois.yaml#L559):

```
           landuse-labels-green-areas-not-national-park:
                filter:
                    all:
                        - area: true
                        - $geometry: point
                        - kind: [park, national_park, "park or protected land", conservation, protected_area, nature_reserve, forest, grass]
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [5],    area: { min: 10000000000 } }
                        - { $zoom: [6,7],  area: { min: 5000000000 } }
                        - { $zoom: [8],    area: { min: 1000000000 } }
                        - { $zoom: [9],    area: { min: 100000000 } }
                        - { $zoom: [10],   area: { min: 50000000 } }
                        - { $zoom: [11],   area: { min: 25000000 } }
                        - { $zoom: [12],   area: { min: 5000000 } }
                        - { $zoom: [13],   area: { min: 200000 } }
                        - { $zoom: [14],   area: { min: 50000 } }
                        - { $zoom: [15],   area: { min: 10000 } }
                        - { $zoom: [16],   area: { min: 1000 } }
                        - { $zoom: { min: 17, area: true } }
```

Maybe should be [like this other line](https://github.com/tangrams/tron/blob/b7d8bae2e271eb22eca5545062d6f60cb3221479/layers/pois.yaml#L961)

```
         playgrounds_allotments_attraction_landmark_supermarket:
                filter:
                    all:
                        - kind: [playground, allotments, attraction, landmark, supermarket]
                        - area: true
                        - $geometry: point
                    any:
                        - { $zoom: [15], area: { min: 600 } }
                        - { $zoom: [16], area: { min: 300 } }
                        - { $zoom: { min: 17 }, area: true }
```

Not really sure...

cc @blair1618 @nvkelso @sensescape

**Comment by patriciogonzalezvivo** [comment] 2016-09-01 16:36
Fixing `opaque` false blend mode here https://github.com/tangrams/tron/commit/6da896af752043cd18cd0c4b0a9ef58244ff6eb3

**Comment by patriciogonzalezvivo** [comment] 2016-09-01 16:40
Fixing the pois bug here https://github.com/tangrams/tron/commit/6f21215e5be293fe19b7aaa87c74027346e82b44

**Comment by patriciogonzalezvivo** [comment] 2016-09-01 17:19
Another one here https://github.com/tangrams/tron/commit/cca483562335658c5fa7d2451a1807397bbb0152

**Comment by patriciogonzalezvivo** [comment] 2016-09-01 17:29
Working on Tangram-ES https://tangrams.github.io/runway/?scene=https://raw.githubusercontent.com/tangrams/tron/gh-pages/tron.yaml

![Uploading Screen Shot 2016-09-01 at 1.28.09 PM.png…]()
<img width="1920" alt="screen shot 2016-09-01 at 1 28 13 pm" src="https://cloud.githubusercontent.com/assets/346914/18177421/2aa81b9e-7048-11e6-99bf-93378cb91065.png">
<img width="1920" alt="screen shot 2016-09-01 at 1 28 34 pm" src="https://cloud.githubusercontent.com/assets/346914/18177422/2aa90086-7048-11e6-9340-78ee8fd3430f.png">
<img width="1920" alt="screen shot 2016-09-01 at 1 28 53 pm" src="https://cloud.githubusercontent.com/assets/346914/18177420/2aa3c8c8-7048-11e6-9172-9cc30cf6c283.png">

![03](https://cloud.githubusercontent.com/assets/346914/18178647/33fd349a-704d-11e6-89f4-b15d052002fa.gif)

**Comment by matteblair** [comment] 2016-09-01 17:47
Huzzah! Do you need any more assistance for tangram-es here?

**Comment by patriciogonzalezvivo** [comment] 2016-09-01 18:03
@blair1618 not very important onces, there are still some [interesting discrepancies between JS and ES.](https://tangrams.github.io/magazine/?scene=https://raw.githubusercontent.com/tangrams/tron/gh-pages/tron.yaml#16/40.7053/-74.0098)
- Like the pink transit lines... in ES are over a bunch of things... while in JS are under
- geometry extrusion 
- And something on the roads... could be a shaders... or a order problem (we are multiplying by 20 what ever is on the vector tile data)

[![00](https://cloud.githubusercontent.com/assets/346914/18178431/4669cb6c-704c-11e6-9b88-e8e4d1b5fc6a.gif)](https://tangrams.github.io/magazine/?scene=https://raw.githubusercontent.com/tangrams/tron/gh-pages/tron.yaml#16/40.7053/-74.0098)

**Comment by nvkelso** [comment] 2016-09-12 22:59
Looking good! Is there any more work to do for this issue?

**Comment by nvkelso** [comment] 2016-09-14 00:58
@patriciogonzalezvivo Can this issue be closed?

**Comment by patriciogonzalezvivo** [comment] 2016-09-14 18:28
@nvkelso the subway lines still apear over earth in tangram-es... here is the  [line](https://tangrams.github.io/magazine/?scene=https://raw.githubusercontent.com/tangrams/tron/gh-pages/tron.yaml#16/40.7053/-74.0098)

Any idea why this happens?? cc @blair1618

**Comment by nvkelso** [comment] 2016-09-14 18:53
@patriciogonzalezvivo I think this matches the Tangram JS behavior, though? (That lines are under buildings in all cases?)

**Comment by patriciogonzalezvivo** [comment] 2016-09-14 19:03
Seams subways are going over street roads in tangram-es 
![screen shot 2016-09-14 at 3 01 42 pm 2](https://cloud.githubusercontent.com/assets/346914/18525876/5e00d21c-7a8c-11e6-888b-768fbcd59368.png)

**Comment by patriciogonzalezvivo** [comment] 2016-09-14 19:05
And yes... is a SUPER detail... probably nobody notice for a while : )
definitely not priority... is more an interesting anomaly that could be useful for the tangram-es team

**Comment by matteblair** [comment] 2016-09-14 19:30
Yeah, can't find anything obviously wrong with the subways specifically. You may want to run this in tangram-es every now and then, there are quite a few syntax errors in the scene file(s) that you'll see warnings for.

**Comment by nvkelso** [comment] 2016-09-20 20:56
@bcamper Can you investigate why Tangram-ES layers transit line on top of everything, while Tangram JS seems to layer them as expected (from the data), please?

**Comment by bcamper** [comment] 2016-09-20 21:28
Probably needs to wait for @blair1618's return.

**Comment by matteblair** [comment] 2016-09-25 22:32
I'll look into this when I get some spare cycles this week

**Comment by tallytalwar** [comment] 2016-09-30 22:29
Is there any other issue, with respect to tangram-es, here other than subway lines being drawn over roads? The issue has been fixed in tangram-es [here](https://github.com/tangrams/tangram-es/commit/f59e0acdc5cbdab2945bfe9d56e586fb811c1b0d).

**Comment by nvkelso** [comment] 2016-10-03 18:10
That's the only one I knew about. Will browse around a bit in Magazine and then close.

**Comment by patriciogonzalezvivo** [comment] 2016-10-03 18:17
@tallytalwar yes... the stripes doesn't show at lower zoom levels : (
I guess is because the alpha

**Comment by patriciogonzalezvivo** [comment] 2016-10-03 18:26
BTW: Paparazzi is currently under repair so no magazine : (

**Comment by tallytalwar** [comment] 2016-10-03 18:33
@patriciogonzalezvivo can you elaborate on the `stripes` issue you have mentioned?

**Comment by patriciogonzalezvivo** [comment] 2016-10-03 19:05
<img width="1920" alt="screen shot 2016-10-03 at 3 04 47 pm" src="https://cloud.githubusercontent.com/assets/346914/19050038/c8261808-897a-11e6-9bc2-20f32cd37a58.png">

**Comment by matteblair** [comment] 2016-10-03 19:15
> I guess is because the alpha

@patriciogonzalezvivo Can you elaborate? Is alpha being used for the stripe pattern?

**Comment by tallytalwar** [comment] 2016-10-03 19:54
I simplified the scene and the `water` style which uses the`polygon-diagnonal-stripes` block style to get the behavior @patriciogonzalezvivo might be describing above:
1. Color alpha is not modifed, rgb modified by the same `diagonalStripes` function:
   ![screen shot 2016-10-03 at 3 47 49 pm](https://cloud.githubusercontent.com/assets/360641/19051505/4896d7ec-8981-11e6-9abd-dda47ea195cf.png)
2. Only alpha is modified, which is not reflecting (debugging this more):
   ![screen shot 2016-10-03 at 3 48 12 pm](https://cloud.githubusercontent.com/assets/360641/19051537/5c90502a-8981-11e6-87cb-a99335b01ee0.png)

**Comment by tallytalwar** [comment] 2016-10-03 20:09
Looks like `color.a` values are not being respected in the scene block injection code. I could be missing something though.

The `water` style has default blending `opaque` so it should not get any alpha blending, which is what is happening on ES.

**Comment by patriciogonzalezvivo** [comment] 2016-10-03 20:10
that's on tangram-es... right?

**Comment by matteblair** [comment] 2016-10-03 20:11
Ohhhh yeah I see, I think this is not quite correct usage of alpha. This works in a WebGL canvas because alpha compositing is a little bit strange. I'll see if we can tweak something with our blending in the style or in the engine, but we may have to change this "block".

**Comment by tallytalwar** [comment] 2016-10-03 20:13
Ohh yeah, this style has default blending, which should not affect the alpha! Hence this.

**Comment by matteblair** [comment] 2016-10-03 20:31
This is not a good solution
_but_
it works correctly if the water style has `blend: inlay`.

**Comment by tallytalwar** [comment] 2016-10-03 21:03
`blend: inlay` will solve this partially. Continuous zooming in-out will have all sorts of wrong blending going on until new tiles get loaded.

Maybe another approach or modification of this block is the best foot forward here.

**Comment by matteblair** [comment] 2016-10-03 22:35
Just to confirm, the problem is that any alpha values, even those from fragments drawn with `opaque` blending, are used for compositing with the canvas background color. This is demonstrated below, produced by changing the canvas `background-color` property to `green`. The canvas background is normally set to `scene.background.color`, which is `black` for tron.

![screen shot 2016-10-03 at 6 31 45 pm](https://cloud.githubusercontent.com/assets/3371850/19056518/ad63946a-8997-11e6-87fd-0efec0ca3493.png)

**Comment by patriciogonzalezvivo** [comment] 2016-10-04 13:18
Solved here: 
https://github.com/tangrams/tron/commit/0fdea20ccb19bd59177a93c5dbc8a1371acfb822

**Comment by patriciogonzalezvivo** [comment] 2016-10-04 13:24
Last discrepancy I notice... @tallytalwar @blair1618 

For the walls of the buildings I'm using a noise mosaic pattern that get faded according to the height percentage of the building using `v_texcoord.y` (here)[https://github.com/tangrams/tron/blob/gh-pages/styles/polygons.yaml#L62]. But seams that tangram-es/tangram.js have them flipped.

<img width="1013" alt="screen shot 2016-10-04 at 9 21 17 am" src="https://cloud.githubusercontent.com/assets/346914/19075748/533aad02-8a14-11e6-8c41-e0003267b94b.png">

Is not necessary a priority... still looks cool... I thought will be interesting to point out

**Comment by patriciogonzalezvivo** [comment] 2016-10-04 14:17
There is other super small differences in font rendering... watch closelly for the **FDR highway** and **Pine St**

![diff](https://cloud.githubusercontent.com/assets/346914/19077747/c252fcec-8a1b-11e6-9a6b-599d7a6151ab.gif)

Note: Tangram Magazine is working again https://tangrams.github.io/magazine/?scene=https://tangrams.github.io/tron/tron.yaml

Note2: JS is on the left and ES on the right

**Comment by tallytalwar** [comment] 2016-10-04 14:39
@patriciogonzalezvivo with respect to the discrepancy with the building mosaic texture, is ES showing the correct behavior and JS the wrong behavior?

**Comment by patriciogonzalezvivo** [comment] 2016-10-04 14:41
@tallytalwar hard to tell what should be right or wrong... I'm just pointing that they don't match ; )

**Comment by tallytalwar** [comment] 2016-10-04 14:43
@patriciogonzalezvivo ok, will see whats the underlying difference here. Thanks

**Comment by tallytalwar** [comment] 2016-10-04 21:51
https://github.com/tangrams/tangram-es/pull/996 should fix the building wall textures. JS and ES should have the same texture coordinates for polygon extrusion post this change.

Will investigate more on the font size issue, that might be linked to the the remote font fix I pushed to master yesterday. Not sure, maybe try a diff with upto date tangram-es master.

**Comment by patriciogonzalezvivo** [comment] 2016-10-04 22:44
thanks @tallytalwar !!! one step closer to JS/ES singularity : )

**Comment by nvkelso** [comment] 2016-10-05 04:22
Let's also remember to refactor the transition YAML syntax mentioned in https://github.com/tangrams/tron/commit/53a1b143b93818b5f1c7c92a3f5856f162275dbc#commitcomment-19296353.

**Comment by nvkelso** [comment] 2016-10-10 05:24
YAML syntax in https://github.com/tangrams/tron/issues/83#issuecomment-251578401 immediately above was addressed in https://github.com/tangrams/tron/commit/5f4882e76cfaa65c1b1d2e920f4fcb48ffb8db05.

**Comment by patriciogonzalezvivo** [comment] 2016-10-11 19:01
so this is issue is done? right?

**Comment by matteblair** [comment] 2016-10-11 23:03
:+1: I'm in favor of closing this and creating new, more specific issues if we still notice discrepancies.

**Comment by nvkelso** [comment] 2016-10-12 07:20
Closing. 

Recommend opening new issues in Tangram ES repo if there are rendering issues (like for the road labels).

**Closed as completed by nvkelso** 2016-10-12 07:20 UTC
Labels: priority1
